version: '3.7'

services:
  backend: &backend
    build:
      context: .
      dockerfile: ./dockerfiles/backend/Dockerfile.local
    volumes:
      - ./:/var/www/backend:cached
      - bundle:/bundle:cached
      - /var/www/backend/log
      - ./tmp:/var/www/backend/tmp
      - /var/www/backend/vendor
    links:
      - mysql
    depends_on:
      - mysql
    command: bash -c "/var/www/backend/services.local.sh"

  mysql:
    image: mysql:5.7.28
    ports:
      - 127.0.0.1:${MYSQL_HOST_PORT}:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql
      - ./docker/mysql/var/lib:/var/lib/mysql

  nginx:
    image: nginx:1.17.5
    volumes:
      - ./docker/nginx/conf.d.local:/etc/nginx/conf.d/
    ports:
      - 127.0.0.1:80:80
    links:
      - backend
    depends_on:
      - backend

volumes:
  bundle:
    driver: local
